### ISSUE TITLE
Slug for every regions

### ISSUE THREAD

**Issue by Marting2105** [aaronmansfield5/SNKRS-Monitor#1]
Hello,
Thanks for the bot. Unfortunately the link is built like this: 
       url:`https://www.nike.com/launch/t/${item.productInfo[0].productContent.slug}`

This gives for example: https://www.nike.com/gb/launch/t/jordan-eastside-golf-trousers (1)

However, this type of training is unique to the UK. There is also a general link, which leads to all regions. I take the example again, here is the general link: 
https://www.nike.com/gb/launch/t/jordan-x-eastside-golf-off-course-apparel-collection-emea (2)

If you have understood, the link that the bot makes is the link (1). But the bot can be the link (2), which allows anyone to consult it from his region.
Thanks in advance

Translated with www.DeepL.com/Translator (free version)

**Comment by Marting2105** [comment]
In more computer terms, 

url:https://www.nike.com/launch/t/${item.productInfo[0].productContent.slug} -> {item.productInfo[0].productContent.slug} = jordan-eastside-golf-trousers

Now the bot must give this slug : jordan-x-eastside-golf-off-course-apparel-collection-emea 

I need to replace {item.productInfo[0].productContent.slug} by another function, can you help me?

**Comment by Marting2105** [comment]
![image](https://user-images.githubusercontent.com/97480952/201537146-e9966621-5464-4b70-bd2e-4b08f99116f3.png)
And maybe something to scrap the price from the region and not always giving prices in GBP.

**Comment by Marting2105** [comment]
![image](https://user-images.githubusercontent.com/97480952/201537198-7c3a9198-4d53-48fd-9844-afde0783eca8.png)
How can the sizes be given in order? Here, the bot gives first the integer numbers then those with comma, it would take the following 5 / 5.5 / 6 / 6.5

**Comment by aaronmansfield5** [comment]
Hey @Marting2105 if you'd like to contact my Discord at teleuser#0983 then I'd be happy to help fix this issue!

**Comment by Marting2105** [comment]
just sent you a request

**Comment by aaronmansfield5** [comment]
The issue was resolved and the new, fixed code has been posted onto the GitHub.
